# ☸️ Kubernetes ConfigMap - BikeMizer
apiVersion: v1
kind: ConfigMap
metadata:
  name: bikemizer-config
  labels:
    app: bikemizer
data:
  # Configurações da aplicação
  node_env: "production"
  port: "3000"
  upload_max_size: "10485760"
  upload_path: "/app/dist/uploads"
  cors_origin: "*"
  
  # Configurações de logging
  log_level: "info"
  log_format: "json"
  
  # Configurações de performance
  max_connections: "100"
  timeout: "30000"
